site_name: Solid-state physics
site_url: https://andy-utas.github.io/

nav:
    - Home: index.md
    - Course particulars: particulars.md
    - 'An introduction to solid-state physics':
      - 'The specific heat of solids I': 01specificheatI.md
      - 'The specific heat of solids II': 02specificheatII.md
      - 'Electrons in metals I': 03emetalsI.md
      - 'Electrons in metals II': 04emetalsII.md
    - Chemistry 101: 05chemistry.md
    - 'One-dimensional solids':
      - 'The tight binding model': 06tightbinding.md
      - 'The diatomic chain': 07diatomic.md
    - 'The geometry of solids':
      - 'Empty content': placeholder.md
    - 'Electrons in solids':
      - 'Empty content': placeholder.md
    - 'Magnetism':
      - 'Empty content': placeholder.md
    - Additional resources: additional.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: logo.png
  favicon: logo.png
  features:
  #  - navigation.expand
    - navigation.top
  highlightjs: True
  # custom_dir: overrides # Initially here for banner usage, but this was not very good

plugins:
  - mkdocs-video
  - search

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tabbed # Enabeles content tabs
  - pymdownx.superfences # Enables nesting of code and content in tabs
  - pymdownx.snippets # Allows for a global list of acronyms
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - footnotes
  - meta

extra_css:
  - 'https://use.fontawesome.com/releases/v5.8.1/css/all.css'
#  - scripts/custom.css
  - stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS_HTML'
  - 'https://unpkg.com/thebelab@0.5.0/lib/index.js'
  - 'scripts/mathjaxhelper.js'
  - 'scripts/thebelabhelper.js'
  - 'scripts/x3dom.js'

copyright: Content prepared and curated by <a href="mailto:andrew.mcculloch@utas.edu.au">A J McCulloch</a>
