site_name: POLUS - UTAS physics
site_url: https://polus.utasphys.cloud.edu.au
repo_url: https://github.com/Andy-UTAS/POLUS
repo_name:  Andy-UTAS/POLUS
edit_uri: ""

nav:
    - Home: index.md
    - 'Part I':
      - partI/index.md
      - partI/s1e01.md
      - partI/s1e02.md
      - partI/s1e04.md
      - partI/s1e05.md
      - partI/s2e02.md
    - 'Part II':
      - partII/index.md
      - partII/adiabatic.md
      - partII/ediffraction.md
      - partII/entropy.md
      - partII/eonm.md
      - partII/hysteresis.md
      - partII/induction.md
      - partII/michelson.md
      - partII/TDR.md
      - partII/ultrasound.md
    - 'Part III':
      - partIII/index.md
      - partIII/gamma.md
      - partIII/muon.md
      - partIII/waveguides.md
      - partIII/nmr.md
      - partIII/xray.md
      - partIII/alpha.md
      - partIII/solar.md
      - partIII/zeeman.md
    - 'Safety':
      - safety/index.md
      - safety/labsafety.md
      - safety/inductions.md
    - 'Reference':
      - reference/index.md
      - reference/experiment.md
      - reference/hardware.md
      - reference/software.md
      - reference/computation.md
      - reference/git.md
      - reference/markdown.md
      - reference/computing.md
      - reference/faqs.md
    - 'Playhouse':
      - playhouse/index.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: logo.png
  favicon: logo.png
  features:
  #  - navigation.expand
    - navigation.top # Include a "back to top" button
    - navigation.tabs # Use tabs rather than sections
    - navigation.sections # Render sections as groups
    - navigation.indexes # Include section index pages
    #- toc.integrate # Integrate the table of contents into the left index
    - search.highlight
    - content.code.annotate
    - announce.dismiss
  highlightjs: True
  icon:
    repo: fontawesome/brands/git-alt
#  custom_dir: overrides # Initially here for banner usage, but this was not very good

plugins:
  - mkdocs-video # allows for video
  - search # enables search
  # - encryptcontent:
      # global_password: 'thisisapassword'
  - git-revision-date-localized:
      type: date
  # - page-to-pdf

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list # For definition lists
  - pymdownx.tasklist: # For lists with checkboxes
      custom_checkbox: true
  - pymdownx.highlight:
      # linenums: true # Enabeles line numbers in code
      linenums_style: pymdownx-inline # Makes the line numbers in code not shit (renders properly and copies well)
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets: # Allows for a global list of acronyms
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences # Enables nesting of code and content in tabs
  - pymdownx.tabbed: # Enabeles content tabs
      alternate_style: true
  - pymdownx.caret
  - pymdownx.keys # Rendering of keyboard keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - attr_list
  - footnotes
  - meta

extra_css:
  - 'https://use.fontawesome.com/releases/v5.8.1/css/all.css'
#  - scripts/custom.css
  - stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS_HTML'
  - 'https://unpkg.com/thebelab@0.5.0/lib/index.js'
  - 'scripts/mathjaxhelper.js'
  - 'scripts/thebelabhelper.js'
  - 'scripts/x3dom.js'

copyright: Content prepared and curated by <a href="mailto:andrew.mcculloch@utas.edu.au">A J McCulloch</a>
